language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - node_modules
script:
  - cd exam_2
  - npm install
  - npm run build
  - тзь к

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $repo_token
  local_dir: ts2/build
  on:
    branch:
      - master
      - gh-pages
      - devel
      - hw5
      - hw7
      - hw7_2sem
