import React, { useState, useEffect } from 'react'
import { useSelector, useDispatch, connect } from 'react-redux'
import { useHistory } from 'react-router-dom'
import TopLineDialogList from '../TopLineDialogList/TopLineDialogList'
import styles from './DialogList.module.css'
import CreateNewChat from '../CreateNewChat/CreateNewChat'
import { openNewChat } from '../../actions/sendMessage'
import { chatFetchData } from '../../actions/middleware'

function getDialogsList() {
  const data = JSON.parse(localStorage.getItem('DialogList'))
  return data == null ? [] : data
}

export function getChat(chatIdParameter) {
  const messages = JSON.parse(localStorage.getItem('messages'))
  const chatInfo = JSON.parse(localStorage.getItem('DialogList'))[chatIdParameter]
  return { chatId: chatIdParameter, topic: chatInfo.topic, messages: messages[chatIdParameter] }
}

const mapStateToProps = (state) => ({
  chats: state.chatList,
})

const mapDispatchToProps = (dispatch) => ({
  openChat: (chatId) => dispatch(chatFetchData(chatId)),
})

//component generated by connect react-redux function
const ChatList = connect(
  mapStateToProps,
  mapDispatchToProps,
)(({ chats, openChat }) => {
  const history = useHistory()
  if (chats == null) return
  return chats.map((chat, index) => (
    <div className={styles.chatwrap} key={index.toString()}>
      <div
        onClick={(e) => {
          history.push(`${window.publicUrl}/chat`)
          openChat(chat.chat_id)
        }}
        role="button"
        tabIndex={0}
        className={styles.wrap}
        id={chat.chat_id}
      >
        <img className={styles.chatImg} src="http://emilcarlsson.se/assets/rachelzane.png" alt="" />
        <div className={styles.meta}>
          <div className={styles.topic}>{`${chat.topic}`} </div>
          <div className={styles.preview}>{chat.lastmessage} </div>
        </div>
        <div className={styles.addinfo}>
          <span className={styles.dot} />
          <p>21:22</p>
        </div>
      </div>
    </div>
  ))
})

function DialogListContainer() {
  const chats = useSelector((state) => state.chatList)
  return (
    <div className={styles.dialogsListContainer}>
      <ChatList />
    </div>
  )
}

function openChat(chatId, dispatch) {
  dispatch(openNewChat(getChat(chatId)))
}

function DialogList() {
  const [chats, setChats] = useState([])
  const loadExistingChats = () => {
    setChats(getDialogsList())
  }
  useEffect(loadExistingChats, [])

  return (
    <div className={styles.dialog_list_wrap}>
      <TopLineDialogList />
      <DialogListContainer chats={chats} setChats={setChats} />
      <CreateNewChat />
    </div>
  )
}

export default DialogList
